#include<iostream> // Required for Printing (ie. cout, endl)
#include <math.h> // Math Library
#include <string> // Used for string
#include <iomanip>
using namespace std;
int main()
{
/*
1) What is the output of the following statements? (Assume int x = 5; int y = 7; at the start of each statement)

a) 5 + ++x = 5 + (1 + 5) = 11
b) --y - x++ = (7 - 1) - 5 = 1
c) ++x * --y = (1 + 5)*(7 - 1) = 36

2) Suppose a, b, and c ae int variables and a = 5 and b = 6. What value is assigned to each variable after each statement executes? 
(If a variable is undefined at a particular statement, report UND undefined)

a = (b++) + 3;           [a= 9,b= 7,c= UND]
c = 2 * a + (++b);       [a= 9,b= 8,c= 26]
b = 2 * (++c) - (a++);   [a= 10,b= 45,c= 27]


3) Assume that the integer object sum contains the value 150 and that the double object average contains the value 12.368 
and that the header files iomanip and iostream have been included. 
Show the output generated by the following code segments. Assume each is an independent code segment.

a) 150  12.368

b) 15012.368

c) 150
   12.368

d) 150
   12

e) 150.12.4

f) 150.12.368

g) 150
   12

h)     12.368
          150

4) Write a program that processes a transaction and prints a receipt to the user. 
The program should first prompt the user for how many Coffee and Doughnuts they are purchasing.
The price for the coffee and doughnuts are 4.99 and 1.99 respectively. The receipt should have a similar format as the example below. 
(Note: Ensure all the currency decimal places line up)
*/

int c, d;
double cPrice(4.99), dPrice(1.99), total, subtotal, cSub, dSub, tax;

cout<< "Welcome to Jim Hortons" << endl;

EnterValue: // Define it at a spot then use "goto" to return to it while the code is running

cout<< "How many Coffee's would you like to order? " << endl;
cin>> c;
cout<< "How many Doughnut's would you like to order? " << endl;
cin>> d;

if (c < 0 || d < 0){
    cout<< "invalid input, enter number > than 0"<< endl;
    goto EnterValue;
}
cSub = cPrice * c;
dSub = dPrice * d;
subtotal = ((cSub) + (dSub));
tax = subtotal * 0.13;
total = subtotal + tax;

cout<< "Here is your receipt: " << endl << "\n";

cout<< "Jim Hortons" << endl << "Customer receipt" << endl;
cout<< endl;
cout<< "Coffee" << setw(12) << "x" << c << setw(12) << setprecision(4) << cSub << "\n";
cout<< "Doughnut" << setw(10) << "x" << d << setw(12) << setprecision(4) << dSub << "\n"<< "\n";
cout<< "Subtotal"<< setw(23) << setprecision(4) << subtotal << "\n";
cout<< "HST"<< setw(17) << "%13"  <<  setw(11) << setprecision(3) << tax << "\n"<< "\n";
cout<< "Total"<< setw(26) << setprecision(4) << total << "\n"<< "\n" << "Thank you for coming!!";

}